In [47]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.preprocessing import StandardScaler

n = 1000 # Объем обучающей выборки
X, y = make_regression(n_samples=n, n_features=10, noise=10.0, random_state=43)
X = StandardScaler().fit_transform(X)

def calc_hessian(X: np.ndarray, n: int = n) -> np.ndarray:
    return (2/n) * X.T @ X

def find_myu_and_L(H: np.ndarray) -> tuple:
    myu = min(np.linalg.eigvals(H))
    L = max(np.linalg.eigvals(H))
    return (myu, L)

H = calc_hessian(X)
m_l = find_myu_and_L(H) # минимальное (μ) и максимальное (L) собственные значения H
k = m_l[1] / m_l[0] # число обусловленности
step = 2 / (m_l[0] + m_l[1]) # оптимальный постоянный шаг

**MSE**: $E(w) = \frac{1}{N} \sum_{i=1}^n (y_{pred_{i}} - y_i)$

$y_{pred} = y(w) = X*W$

В матричном виде:

$E(w) = \frac{1}{N} ||X*W - y||^2 = \frac{1}{N} (X*W - y)^T * (X*W - y) = \frac{1}{N} (W^T X^T X W - 2y^T X W - y^T y)$



$\nabla E(w) = \frac{2}{N} X^T (XW - y)$

In [ ]:
def gradient(X, y, weights):
    return (2/len(y)) * X.T @ (X @ weights - y)

def batch_gd(
    X, y, lr: float=0.01, n_iter: int=100
):
    weights = # init_w
    for n in range(n_iter):
        grad = gradient(X, y, weights)
        weights = lr*
    return None

def sgd(
    X, y, lr: float=0.01, batch_size: int=32,
    n_iter: int=1000
):
    return None

def sgd_momentum(
    X, y,
    lr: float=0.01, batch_size: int=32,
    momentum: float=0.4, n_iter: int=1000
):
    return None

In [41]:
er = np.array([
    [1,1,1],
    [2,2,2]])

print(er)

print(er.T)
some_res = er.T @ er
print(some_res)

egval = np.linalg.eigvals(some_res)
print(egval)
print(min(egval))

[[1 1 1]
 [2 2 2]]
[[1 2]
 [1 2]
 [1 2]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[ 1.50000000e+01 -4.04617476e-16  2.46519033e-32]
-4.0461747552072276e-16
